version: 2.1

jobs:
	build:
		docker:
			- image: circleci/python:3.6.1
		working_directory: ~/repo
		steps:
			- checkout
			- run:
					name: Install Dependencies
					command: |
						make install
			-run:
					name: Linting files
					command: |
						make lint